from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(967, 904)
        self.filename = QtWidgets.QTextEdit(Dialog)
        self.filename.setEnabled(True)
        self.filename.setGeometry(QtCore.QRect(0, 50, 231, 61))
        self.filename.setObjectName("filename")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, -10, 171, 71))
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 210, 181, 151))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_field = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_field.setObjectName("radioButton_field")
        self.verticalLayout_2.addWidget(self.radioButton_field)
        self.radioButton_forest = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_forest.setObjectName("radioButton_forest")
        self.verticalLayout_2.addWidget(self.radioButton_forest)
        self.radioButton_ocean = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_ocean.setObjectName("radioButton_ocean")
        self.verticalLayout_2.addWidget(self.radioButton_ocean)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(250, 0, 711, 451))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.checkBox_animals = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_animals.setEnabled(False)
        self.checkBox_animals.setObjectName("checkBox_animals")
        self.horizontalLayout_13.addWidget(self.checkBox_animals)
        self.spinBox_animals = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_animals.setEnabled(False)
        self.spinBox_animals.setMinimum(1)
        self.spinBox_animals.setMaximum(5)
        self.spinBox_animals.setObjectName("spinBox_animals")
        self.horizontalLayout_13.addWidget(self.spinBox_animals)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_path = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_path.setEnabled(False)
        self.checkBox_path.setObjectName("checkBox_path")
        self.horizontalLayout_8.addWidget(self.checkBox_path)
        self.spinBox_path = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_path.setEnabled(False)
        self.spinBox_path.setMinimum(1)
        self.spinBox_path.setMaximum(4)
        self.spinBox_path.setObjectName("spinBox_path")
        self.horizontalLayout_8.addWidget(self.spinBox_path)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBox_fence = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_fence.setEnabled(False)
        self.checkBox_fence.setObjectName("checkBox_fence")
        self.horizontalLayout_10.addWidget(self.checkBox_fence)
        self.spinBox_fence = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_fence.setEnabled(False)
        self.spinBox_fence.setMinimum(4)
        self.spinBox_fence.setMaximum(10)
        self.spinBox_fence.setObjectName("spinBox_fence")
        self.horizontalLayout_10.addWidget(self.spinBox_fence)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.checkBox_fish = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_fish.setEnabled(False)
        self.checkBox_fish.setObjectName("checkBox_fish")
        self.horizontalLayout_14.addWidget(self.checkBox_fish)
        self.spinBox_fish = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_fish.setEnabled(False)
        self.spinBox_fish.setMinimum(1)
        self.spinBox_fish.setMaximum(5)
        self.spinBox_fish.setObjectName("spinBox_fish")
        self.horizontalLayout_14.addWidget(self.spinBox_fish)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_boat = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_boat.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_boat.sizePolicy().hasHeightForWidth())
        self.checkBox_boat.setSizePolicy(sizePolicy)
        self.checkBox_boat.setCheckable(True)
        self.checkBox_boat.setObjectName("checkBox_boat")
        self.horizontalLayout_7.addWidget(self.checkBox_boat)
        self.spinBox_boat = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_boat.setEnabled(False)
        self.spinBox_boat.setMinimum(1)
        self.spinBox_boat.setMaximum(4)
        self.spinBox_boat.setObjectName("spinBox_boat")
        self.horizontalLayout_7.addWidget(self.spinBox_boat)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBox_lighthouse = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_lighthouse.setEnabled(False)
        self.checkBox_lighthouse.setObjectName("checkBox_lighthouse")
        self.horizontalLayout_12.addWidget(self.checkBox_lighthouse)
        self.spinBox_lighthouse = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_lighthouse.setEnabled(False)
        self.spinBox_lighthouse.setMinimum(1)
        self.spinBox_lighthouse.setMaximum(2)
        self.spinBox_lighthouse.setObjectName("spinBox_lighthouse")
        self.horizontalLayout_12.addWidget(self.spinBox_lighthouse)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.checkBox_sun = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_sun.setEnabled(True)
        self.checkBox_sun.setObjectName("checkBox_sun")
        self.verticalLayout_3.addWidget(self.checkBox_sun)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_cloud = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_cloud.setEnabled(True)
        self.checkBox_cloud.setObjectName("checkBox_cloud")
        self.horizontalLayout_4.addWidget(self.checkBox_cloud)
        self.spinBox_cloud = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_cloud.setEnabled(False)
        self.spinBox_cloud.setMinimum(1)
        self.spinBox_cloud.setMaximum(5)
        self.spinBox_cloud.setObjectName("spinBox_cloud")
        self.horizontalLayout_4.addWidget(self.spinBox_cloud)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_house = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox_house.setEnabled(True)
        self.checkBox_house.setObjectName("checkBox_house")
        self.horizontalLayout_9.addWidget(self.checkBox_house)
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        self.checkBox.setEnabled(False)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_9.addWidget(self.checkBox)
        self.spinBox_house = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.spinBox_house.setEnabled(False)
        self.spinBox_house.setMinimum(1)
        self.spinBox_house.setMaximum(2)
        self.spinBox_house.setObjectName("spinBox_house")
        self.horizontalLayout_9.addWidget(self.spinBox_house)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 520, 941, 72))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tree = QtWidgets.QCheckBox(self.layoutWidget)
        self.tree.setEnabled(False)
        self.tree.setObjectName("tree")
        self.horizontalLayout.addWidget(self.tree)
        self.spinBox_tree = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_tree.setEnabled(False)
        self.spinBox_tree.setMinimum(1)
        self.spinBox_tree.setMaximum(12)
        self.spinBox_tree.setObjectName("spinBox_tree")
        self.horizontalLayout.addWidget(self.spinBox_tree)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 620, 941, 81))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mount = QtWidgets.QCheckBox(self.layoutWidget1)
        self.mount.setEnabled(True)
        self.mount.setObjectName("mount")
        self.horizontalLayout_2.addWidget(self.mount)
        self.spinBox_mount = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spinBox_mount.setEnabled(False)
        self.spinBox_mount.setMinimum(1)
        self.spinBox_mount.setMaximum(8)
        self.spinBox_mount.setObjectName("spinBox_mount")
        self.horizontalLayout_2.addWidget(self.spinBox_mount)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 730, 941, 71))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.time = QtWidgets.QCheckBox(self.layoutWidget2)
        self.time.setEnabled(True)
        self.time.setObjectName("time")
        self.horizontalLayout_5.addWidget(self.time)
        self.radioButton_morning = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_morning.setEnabled(False)
        self.radioButton_morning.setObjectName("radioButton_morning")
        self.horizontalLayout_5.addWidget(self.radioButton_morning)
        self.radioButton_day = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_day.setEnabled(False)
        self.radioButton_day.setObjectName("radioButton_day")
        self.horizontalLayout_5.addWidget(self.radioButton_day)
        self.radioButton_evening = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_evening.setEnabled(False)
        self.radioButton_evening.setObjectName("radioButton_evening")
        self.horizontalLayout_5.addWidget(self.radioButton_evening)
        self.radioButton_night = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_night.setEnabled(False)
        self.radioButton_night.setObjectName("radioButton_night")
        self.horizontalLayout_5.addWidget(self.radioButton_night)
        self.radioButton_now = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioButton_now.setEnabled(False)
        self.radioButton_now.setObjectName("radioButton_now")
        self.horizontalLayout_5.addWidget(self.radioButton_now)
        self.layoutWidget3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 830, 941, 71))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.season = QtWidgets.QCheckBox(self.layoutWidget3)
        self.season.setEnabled(True)
        self.season.setObjectName("season")
        self.horizontalLayout_6.addWidget(self.season)
        self.radioButton_summer = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioButton_summer.setEnabled(False)
        self.radioButton_summer.setObjectName("radioButton_summer")
        self.horizontalLayout_6.addWidget(self.radioButton_summer)
        self.radioButton_auttom = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioButton_auttom.setEnabled(False)
        self.radioButton_auttom.setObjectName("radioButton_auttom")
        self.horizontalLayout_6.addWidget(self.radioButton_auttom)
        self.radioButton_winter = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioButton_winter.setEnabled(False)
        self.radioButton_winter.setObjectName("radioButton_winter")
        self.horizontalLayout_6.addWidget(self.radioButton_winter)
        self.radioButton_spring = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioButton_spring.setEnabled(False)
        self.radioButton_spring.setObjectName("radioButton_spring")
        self.horizontalLayout_6.addWidget(self.radioButton_spring)
        self.radioButton_now_season = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioButton_now_season.setEnabled(False)
        self.radioButton_now_season.setObjectName("radioButton_now_season")
        self.horizontalLayout_6.addWidget(self.radioButton_now_season)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(10, 474, 171, 41))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(180, 470, 321, 41))
        self.label_3.setMaximumSize(QtCore.QSize(16777195, 16777215))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 221, 81))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(0, 370, 227, 71))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.filename.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16.2pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; font-style:italic;\">Prototip.png</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Название"))
        self.radioButton_field.setText(_translate("Dialog", "Поляна"))
        self.radioButton_forest.setText(_translate("Dialog", "Лес"))
        self.radioButton_ocean.setText(_translate("Dialog", "Океан"))
        self.checkBox_animals.setText(_translate("Dialog", "Звери"))
        self.checkBox_path.setText(_translate("Dialog", "Тропинка"))
        self.checkBox_fence.setText(_translate("Dialog", "Забор"))
        self.checkBox_fish.setText(_translate("Dialog", "Рыбы"))
        self.checkBox_boat.setText(_translate("Dialog", "Корабль"))
        self.checkBox_lighthouse.setText(_translate("Dialog", "Маяк"))
        self.checkBox_sun.setText(_translate("Dialog", "Солнце/луна"))
        self.checkBox_cloud.setText(_translate("Dialog", "Облака"))
        self.checkBox_house.setText(_translate("Dialog", "Дом"))
        self.checkBox.setText(_translate("Dialog", "цвет крыши"))
        self.tree.setText(_translate("Dialog", "Деревья"))
        self.mount.setText(_translate("Dialog", "Горы"))
        self.time.setText(_translate("Dialog", "Время суток"))
        self.radioButton_morning.setText(_translate("Dialog", "Утро"))
        self.radioButton_day.setText(_translate("Dialog", "День"))
        self.radioButton_evening.setText(_translate("Dialog", "Вечер"))
        self.radioButton_night.setText(_translate("Dialog", "Ночь"))
        self.radioButton_now.setText(_translate("Dialog", "Нынешнее"))
        self.season.setText(_translate("Dialog", "Сезон погоды"))
        self.radioButton_summer.setText(_translate("Dialog", "Лето"))
        self.radioButton_auttom.setText(_translate("Dialog", "Осень"))
        self.radioButton_winter.setText(_translate("Dialog", "Зима"))
        self.radioButton_spring.setText(_translate("Dialog", "Весна"))
        self.radioButton_now_season.setText(_translate("Dialog", "Нынешнее"))
        self.label_3.setText(_translate("Dialog", "Заполненность картинки"))
        self.label_4.setText(_translate("Dialog", "Выберите, где \n"
"будет картинка"))
        self.pushButton.setText(_translate("Dialog", "Создать картинку"))
